### ISSUE TITLE
"/dogs" post

### ISSUE THREAD

**Issue by glrta** [fac19/week8-DEKN#14]
- [x] grab input values
- [x] redirect to all dogs and show latest at the top

**Comment by jackherizsmith** [comment]
Hey @glrta! :service_dog: 

To sort by most recent dogs, once you have the full list back you could get all their IDs and sort them largest to smallest using:

`dogs.sort(function(a, b){return b-a});` :poodle: :guide_dog: :dog2: 

Hope that  helps!
