### ISSUE TITLE
Semantic tags

### ISSUE THREAD

**Issue by jackherizsmith** [fac19/week8-DEKN#47]
Could be worth auditing your site for `div`s, e.g. the error message on your forms could be a `<p>`?

**Comment by oliverjam** [comment]
There's nothing inherently _wrong_ with divs, they just have no semantic meaning. If the element you're creating doesn't fit with any existing HTML elements then divs are absolutely allowed.

I've always been torn on using `p`s outside of longer form article text. It's probably fine to use for an error message, but it's probably not necessary either.
